### PR TITLE
Add My Profile To Wall

### PR DESCRIPTION
**Pull request by knightmate**
This is Pr is done after taking the fresh upsteam from development and master

### CODE REVIEW

**Review by shivamyth — CHANGES_REQUESTED** [review]
Delete  all DS_Store files

**Comment by knightmate** [comment]
Done, Please checkout

**Review by shivamyth — CHANGES_REQUESTED** [review]
There are still two DS_Store files, Delete them

**Comment by shivamyth** [comment]
No updates on the PR, closing it for now.

**Pull request closed without merging**
