### PR TITLE
  Create 2020 folder for  6th-jan-career-camp  batch 

### PR DESCRIPTION
**Pull request by rks107**
please view my pull request for the same. and kindly give me feedback where I am wrong.
thank you.

### CODE REVIEW

**Review by dakshkhetan — CHANGES_REQUESTED** [review]
Hey @rks107 , please take a fresh pull from development branch by running command git pull upstream development and then redo the whole process of adding your profile/resume. :)

**Comment by dakshkhetan** [comment]
Closing this PR for now, please raise a new one after doing the process again.

**Comment by rks107** [comment]
thanks for reviewing
In-place of *git pull upstream development* command, I were run "*git
remote add upstream
https://github.com/CodingNinjasCodes/wall-of-developers.git
<https://github.com/CodingNinjasCodes/wall-of-developers.git>*" command
just after clone.
is it not work for "fresh update of the code anytime in the future" ?

**Comment by dakshkhetan** [comment]
First, you need to set upstream which is `https://github.com/CodingNinjasCodes/wall-of-developers.git` (you can refer to the `readme.md` of Wall Of Developers).
Then, you need to fetch the new changes from the main repo to your forked repo by running command `git pull upstream development` in terminal.

**Pull request closed without merging**
